<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.text.SimpleDateFormat,com.slf.model.ThirdPartyAcceptanceResult,com.slf.model.ThirdPartyAccessRequest,com.slf.model.ThirdPartyFormSubmission,com.slf.model.ThirdPartyRequest" %>
<%!
private String h(Object input){if(input==null)return "";return String.valueOf(input).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private String display(Object input){return input==null||String.valueOf(input).trim().isEmpty()?"-":h(input);}
%>
<%
ThirdPartyRequest thirdPartyRequest=(ThirdPartyRequest)request.getAttribute("thirdPartyRequest");
ThirdPartyFormSubmission submission=(ThirdPartyFormSubmission)request.getAttribute("submission");
ThirdPartyAcceptanceResult acceptance=(ThirdPartyAcceptanceResult)request.getAttribute("acceptanceResult");
String sectionHeadComment=(String)request.getAttribute("sectionHeadComment"),itDirectorComment=(String)request.getAttribute("itDirectorComment"),operatorComment=(String)request.getAttribute("operatorComment"),revokerComment=(String)request.getAttribute("revokerComment");
String pageRole=(String)request.getAttribute("pageRole"),pageTitle=(String)request.getAttribute("pageTitle"),detailLabel=(String)request.getAttribute("detailLabel"),detailParameter=(String)request.getAttribute("detailParameter"),formAction=(String)request.getAttribute("formAction"),csrfToken=(String)request.getAttribute("csrfToken"),formError=(String)request.getAttribute("formError");
boolean showRevokerComment=Boolean.TRUE.equals(request.getAttribute("showRevokerComment"));
String currentDetail=request.getParameter(detailParameter); SimpleDateFormat dateOnly=new SimpleDateFormat("dd/MM/yyyy");
%>
<!DOCTYPE html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><%= h(pageTitle) %> Third-party #<%= thirdPartyRequest.getRequestId() %></title>
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/styles.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
<style>
.assigned-review{max-width:1180px;margin:0 auto;padding:28px 28px 48px}.review-panel{background:#fff;border:1px solid #d9e6f2;border-radius:10px;padding:22px;margin-bottom:18px;box-shadow:0 8px 22px rgba(0,51,102,.06)}.review-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px 20px}.review-field{border-bottom:1px solid #e5eef6;padding-bottom:10px}.review-field.full{grid-column:1/-1}.review-label{color:#64748b;font-size:13px;font-weight:800;margin-bottom:5px}.review-value{color:#102a43;line-height:1.55;white-space:pre-wrap;overflow-wrap:anywhere}.access-item{border:1px solid #d9e6f2;border-radius:8px;padding:16px;margin-top:14px}.comment-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.comment-card{padding:16px;border-radius:8px;background:#f6f9fc;border:1px solid #d9e6f2}.acceptance-card{background:#f0fdf4;border-color:#bbf7d0}.detail-box textarea{width:100%;min-height:150px;border:1px solid #bfd0df;border-radius:7px;padding:12px;font:inherit;resize:vertical}.submit-row{display:flex;justify-content:flex-end;margin-top:18px}@media(max-width:800px){.assigned-review{padding:18px 14px 36px}.review-grid,.comment-grid{grid-template-columns:1fr}.review-field.full{grid-column:auto}.submit-row button{width:100%}}
</style></head><body>
<%@ include file="/WEB-INF/jspf/sidebar.jspf" %><div id="main"><%@ include file="/WEB-INF/jspf/topbar.jspf" %>
<main class="assigned-review"><section class="third-party-page-head"><div><p class="eyebrow">Third-party Workflow · <%= h(pageRole) %></p><h1><%= h(pageTitle) %> คำขอ #<%= thirdPartyRequest.getRequestId() %></h1><p>ตรวจสอบข้อมูลและบันทึกรายละเอียดงานเพื่อส่งต่อขั้นตอนถัดไป</p></div></section>
<% if(formError!=null){ %><div class="form-alert"><%= h(formError) %></div><% } %>
<section class="review-panel"><h2 class="form-section-title">ข้อมูลผู้ขอและรายละเอียดการใช้งาน</h2><div class="review-grid">
<div class="review-field"><div class="review-label">ชื่อ-สกุล</div><div class="review-value"><%= display(submission.getFullNameTh()) %></div></div><div class="review-field"><div class="review-label">หน่วยงาน</div><div class="review-value"><%= display(submission.getOrganization()) %></div></div>
<div class="review-field"><div class="review-label">Email</div><div class="review-value"><%= display(submission.getEmail()) %></div></div><div class="review-field"><div class="review-label">เบอร์โทรศัพท์</div><div class="review-value"><%= display(submission.getPhone()) %></div></div>
<div class="review-field full"><div class="review-label">เหตุผลและวัตถุประสงค์</div><div class="review-value"><%= display(submission.getReasonObjective()) %></div></div><div class="review-field"><div class="review-label">วันที่เริ่มต้น</div><div class="review-value"><%= submission.getAccessStartDate()==null?"-":dateOnly.format(submission.getAccessStartDate()) %></div></div><div class="review-field"><div class="review-label">วันที่สิ้นสุด</div><div class="review-value"><%= submission.getAccessEndDate()==null?"-":dateOnly.format(submission.getAccessEndDate()) %></div></div>
</div></section>
<section class="review-panel"><h2 class="form-section-title">รายการผู้ขอรับสิทธิ์</h2><% for(ThirdPartyAccessRequest item:submission.getAccessRequests()){ %><article class="access-item"><div class="review-grid"><div class="review-field"><div class="review-label">ชื่อ-สกุล</div><div class="review-value"><%= display(item.getFullNameTh()) %></div></div><div class="review-field"><div class="review-label">Username</div><div class="review-value"><%= display(item.getUsername()) %></div></div><div class="review-field"><div class="review-label">ระบบงาน</div><div class="review-value"><%= display(item.getSystemName()) %></div></div><div class="review-field"><div class="review-label">สิทธิ์การใช้งาน</div><div class="review-value"><%= display(item.getRequestedRole()) %></div></div></div></article><% } %></section>
<section class="review-panel"><h2 class="form-section-title">ประวัติการดำเนินงาน</h2><div class="comment-grid">
<div class="comment-card"><div class="review-label">ความเห็นหัวหน้าส่วน</div><div class="review-value"><%= display(sectionHeadComment) %></div></div><div class="comment-card"><div class="review-label">ความเห็น IT Director</div><div class="review-value"><%= display(itDirectorComment) %></div></div><div class="comment-card"><div class="review-label">รายละเอียดการให้สิทธิ์</div><div class="review-value"><%= display(operatorComment) %></div></div>
<% if(showRevokerComment){ %><div class="comment-card"><div class="review-label">รายละเอียดการยกเลิกสิทธิ์</div><div class="review-value"><%= display(revokerComment) %></div></div><% } %>
<div class="comment-card acceptance-card"><div class="review-label">ผลตรวจรับและประเมิน</div><div class="review-value">ระดับความพึงพอใจ: <%= acceptance==null?"-":acceptance.getSatisfactionLevel() %><br><%= acceptance==null?"-":display(acceptance.getCommentText()) %></div></div>
</div></section>
<section class="review-panel detail-box"><h2 class="form-section-title"><%= h(detailLabel) %></h2><form method="post" action="${pageContext.request.contextPath}<%= h(formAction) %>"><input type="hidden" name="csrfToken" value="<%= h(csrfToken) %>"><input type="hidden" name="requestId" value="<%= thirdPartyRequest.getRequestId() %>"><textarea name="<%= h(detailParameter) %>" maxlength="4000" required placeholder="กรอกรายละเอียด..."><%= h(currentDetail) %></textarea><div class="submit-row"><button class="workflow-submit-button" type="submit" data-workflow-confirm data-confirm-title="ส่งผลตรวจรับและประเมินเสร็จสิ้น" data-confirm-message="รายละเอียดจะถูกบันทึกและส่งงานไปยังขั้นตอนถัดไป" data-confirm-label="ยืนยันส่งต่อ"><i class="fa-solid fa-paper-plane"></i> บันทึกและส่งต่อ</button></div></form></section>
</main><%@ include file="/WEB-INF/jspf/footer.jspf" %></div>
<%@ include file="/WEB-INF/jspf/third-party-confirm-dialog.jspf" %>
<script>window.addEventListener("pageshow",function(e){if(e.persisted)window.location.replace("${pageContext.request.contextPath}/thirdParty/operator");});function toggleNav(){var s=document.getElementById("mySidebar"),m=document.getElementById("main"),o=s.style.width==="250px";s.style.width=o?"0":"250px";m.style.marginLeft=o?"0":"250px";m.style.width=o?"100%":"calc(100% - 250px)";}</script>
</body></html>
