<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ page import="java.text.SimpleDateFormat,java.util.Collections,java.util.List,com.slf.model.ThirdPartyAcceptanceResult,com.slf.model.ThirdPartyAccessRequest,com.slf.model.ThirdPartyFormSubmission,com.slf.model.ThirdPartyRequest,com.slf.model.ThirdPartyWorkflowAssignment" %>
<%!
private String h(Object input){if(input==null)return "";return String.valueOf(input).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&#39;");}
private String display(Object input){return input==null||String.valueOf(input).trim().isEmpty()?"-":h(input);}
private String role(String value){if("GRANT_OPERATOR".equals(value))return "ผู้ดำเนินการให้สิทธิ์";if("REVOKE_OPERATOR".equals(value))return "ผู้ยกเลิกสิทธิ์";if("REVOKE_REVIEWER".equals(value))return "ผู้ตรวจทาน";return value;}
%>
<%
ThirdPartyRequest thirdPartyRequest=(ThirdPartyRequest)request.getAttribute("thirdPartyRequest"); ThirdPartyFormSubmission submission=(ThirdPartyFormSubmission)request.getAttribute("submission"); ThirdPartyAcceptanceResult acceptance=(ThirdPartyAcceptanceResult)request.getAttribute("acceptanceResult");
List<ThirdPartyWorkflowAssignment> assignments=(List<ThirdPartyWorkflowAssignment>)request.getAttribute("assignments");if(assignments==null)assignments=Collections.emptyList();
String sectionHeadComment=(String)request.getAttribute("sectionHeadComment"),itDirectorComment=(String)request.getAttribute("itDirectorComment"),operatorComment=(String)request.getAttribute("operatorComment"),revokerComment=(String)request.getAttribute("revokerComment"),reviewerComment=(String)request.getAttribute("reviewerComment"),sectionHeadReport=(String)request.getAttribute("sectionHeadReport");
String pageRole=(String)request.getAttribute("pageRole"),pageTitle=(String)request.getAttribute("pageTitle"),formAction=(String)request.getAttribute("formAction"),inboxPath=(String)request.getAttribute("inboxPath"),csrfToken=(String)request.getAttribute("csrfToken"),formError=(String)request.getAttribute("formError"); boolean showReportField=Boolean.TRUE.equals(request.getAttribute("showReportField"));String currentReport=request.getParameter("summaryReport");SimpleDateFormat dateOnly=new SimpleDateFormat("dd/MM/yyyy");
%>
<!DOCTYPE html><html lang="th"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><%= h(pageTitle) %> #<%= thirdPartyRequest.getRequestId() %></title>
<link rel="stylesheet" href="${pageContext.request.contextPath}/css/styles.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
<style>.page{max-width:1180px;margin:0 auto;padding:28px 28px 48px}.panel{background:#fff;border:1px solid #d9e6f2;border-radius:10px;padding:22px;margin-bottom:18px;box-shadow:0 8px 22px rgba(0,51,102,.06)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px 20px}.field{border-bottom:1px solid #e5eef6;padding-bottom:10px}.full{grid-column:1/-1}.label{color:#64748b;font-size:13px;font-weight:800;margin-bottom:5px}.value{color:#102a43;line-height:1.55;white-space:pre-wrap;overflow-wrap:anywhere}.access{border:1px solid #d9e6f2;border-radius:8px;padding:16px;margin-top:14px}.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.card{padding:16px;border-radius:8px;background:#f6f9fc;border:1px solid #d9e6f2}.accept{background:#f0fdf4;border-color:#bbf7d0}.report textarea{width:100%;min-height:150px;border:1px solid #bfd0df;border-radius:7px;padding:12px;font:inherit}.submit{display:flex;justify-content:flex-end;margin-top:18px}@media(max-width:800px){.page{padding:18px 14px}.grid,.cards{grid-template-columns:1fr}.full{grid-column:auto}.submit button{width:100%}}</style></head><body>
<%@ include file="/WEB-INF/jspf/sidebar.jspf" %><div id="main"><%@ include file="/WEB-INF/jspf/topbar.jspf" %><main class="page"><section class="third-party-page-head"><div><p class="eyebrow">Third-party Workflow · <%= h(pageRole) %></p><h1><%= h(pageTitle) %> คำขอ #<%= thirdPartyRequest.getRequestId() %></h1><p>ตรวจสอบข้อมูลและประวัติการดำเนินงานทั้งหมดก่อนส่งต่อหรือรับรองแบบฟอร์ม</p></div></section>
<% if(formError!=null){ %><div class="form-alert"><%= h(formError) %></div><% } %>
<section class="panel"><h2 class="form-section-title">ข้อมูลผู้ขอและรายละเอียดการใช้งาน</h2><div class="grid"><div class="field"><div class="label">ชื่อ-สกุล</div><div class="value"><%= display(submission.getFullNameTh()) %></div></div><div class="field"><div class="label">หน่วยงาน</div><div class="value"><%= display(submission.getOrganization()) %></div></div><div class="field"><div class="label">Email</div><div class="value"><%= display(submission.getEmail()) %></div></div><div class="field"><div class="label">เบอร์โทรศัพท์</div><div class="value"><%= display(submission.getPhone()) %></div></div><div class="field full"><div class="label">เหตุผลและวัตถุประสงค์</div><div class="value"><%= display(submission.getReasonObjective()) %></div></div><div class="field"><div class="label">วันที่เริ่มต้น</div><div class="value"><%= submission.getAccessStartDate()==null?"-":dateOnly.format(submission.getAccessStartDate()) %></div></div><div class="field"><div class="label">วันที่สิ้นสุด</div><div class="value"><%= submission.getAccessEndDate()==null?"-":dateOnly.format(submission.getAccessEndDate()) %></div></div></div></section>
<section class="panel"><h2 class="form-section-title">รายการผู้ขอรับสิทธิ์</h2><% for(ThirdPartyAccessRequest item:submission.getAccessRequests()){ %><article class="access"><div class="grid"><div class="field"><div class="label">ชื่อ-สกุล</div><div class="value"><%= display(item.getFullNameTh()) %></div></div><div class="field"><div class="label">Username</div><div class="value"><%= display(item.getUsername()) %></div></div><div class="field"><div class="label">ระบบงาน</div><div class="value"><%= display(item.getSystemName()) %></div></div><div class="field"><div class="label">สิทธิ์การใช้งาน</div><div class="value"><%= display(item.getRequestedRole()) %></div></div></div></article><% } %></section>
<section class="panel"><h2 class="form-section-title">ผู้ได้รับมอบหมาย</h2><div class="cards"><% for(ThirdPartyWorkflowAssignment item:assignments){ %><div class="card"><div class="label"><%= h(role(item.getAssignmentRole())) %></div><div class="value"><%= display(item.getAssignedEmpName()) %> (ID: <%= item.getAssignedEmpId() %>)</div></div><% } %></div></section>
<section class="panel"><h2 class="form-section-title">ข้อมูลและประวัติการดำเนินงานทั้งหมด</h2><div class="cards"><div class="card"><div class="label">ความเห็นหัวหน้าส่วน</div><div class="value"><%= display(sectionHeadComment) %></div></div><div class="card"><div class="label">ความเห็น IT Director</div><div class="value"><%= display(itDirectorComment) %></div></div><div class="card"><div class="label">รายละเอียดการให้สิทธิ์</div><div class="value"><%= display(operatorComment) %></div></div><div class="card accept"><div class="label">ผลตรวจรับและประเมิน</div><div class="value">ระดับความพึงพอใจ: <%= acceptance==null?"-":acceptance.getSatisfactionLevel() %><br><%= acceptance==null?"-":display(acceptance.getCommentText()) %></div></div><div class="card"><div class="label">รายละเอียดการยกเลิกสิทธิ์</div><div class="value"><%= display(revokerComment) %></div></div><div class="card"><div class="label">รายละเอียดการตรวจทาน</div><div class="value"><%= display(reviewerComment) %></div></div><% if(!showReportField){ %><div class="card full"><div class="label">รายงานสรุปหัวหน้าส่วน</div><div class="value"><%= display(sectionHeadReport) %></div></div><% } %></div></section>
<section class="panel report"><form method="post" action="${pageContext.request.contextPath}<%= h(formAction) %>"><input type="hidden" name="csrfToken" value="<%= h(csrfToken) %>"><input type="hidden" name="requestId" value="<%= thirdPartyRequest.getRequestId() %>"><% if(showReportField){ %><h2 class="form-section-title">รายงานสรุป</h2><textarea name="summaryReport" maxlength="4000" required placeholder="กรอกรายงานสรุป..."><%= h(currentReport) %></textarea><% } %><div class="submit"><button class="btn btn-primary primary-action" type="submit" onclick="return confirm('<%= showReportField?"ยืนยันการบันทึกรายงานและส่งให้ IT Director หรือไม่?":"ยืนยันการเซ็นรับรองและปิดแบบฟอร์มนี้หรือไม่?" %>')"><i class="fa-solid fa-check"></i> <%= showReportField?"บันทึกรายงานและส่งต่อ":"อนุมัติและเซ็นรับรองแบบฟอร์ม" %></button></div></form></section>
</main><%@ include file="/WEB-INF/jspf/footer.jspf" %></div><script>window.addEventListener("pageshow",function(e){if(e.persisted)window.location.replace("${pageContext.request.contextPath}<%= h(inboxPath) %>");});function toggleNav(){var s=document.getElementById("mySidebar"),m=document.getElementById("main"),o=s.style.width==="250px";s.style.width=o?"0":"250px";m.style.marginLeft=o?"0":"250px";m.style.width=o?"100%":"calc(100% - 250px)";}</script></body></html>
