BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_NOTIFICATION_LOG ADD LAST_ATTEMPT_AT TIMESTAMP';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_NOTIFICATION_LOG ADD NEXT_ATTEMPT_AT TIMESTAMP DEFAULT SYSTIMESTAMP';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

UPDATE EMAIL_NOTIFICATION_LOG
SET NEXT_ATTEMPT_AT = SYSTIMESTAMP
WHERE STATUS IN ('READY', 'PENDING', 'FAILED')
  AND NEXT_ATTEMPT_AT IS NULL;

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_NOTIFICATION_LOG DROP CONSTRAINT CHK_EMAIL_NOTIFICATION_STATUS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
        END IF;
END;
/

ALTER TABLE EMAIL_NOTIFICATION_LOG ADD CONSTRAINT CHK_EMAIL_NOTIFICATION_STATUS
CHECK (STATUS IN ('READY', 'PENDING', 'SENDING', 'SENT', 'FAILED', 'SKIPPED'));

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_EMAIL_NOTI_LOG_DUE ON EMAIL_NOTIFICATION_LOG (STATUS, NEXT_ATTEMPT_AT)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
