-- Remove unused links previously kept as REVOKED/CANCELLED by the owner flow.
-- Submitted links are preserved.

DELETE FROM THIRD_PARTY_FORM_LINK l
WHERE l.REQUEST_ID IS NOT NULL
  AND l.STATUS = 'REVOKED'
  AND l.SUBMIT_COUNT = 0
  AND NOT EXISTS (
      SELECT 1
      FROM THIRD_PARTY_FORM_SUBMISSION s
      WHERE s.LINK_ID = l.LINK_ID
  )
  AND EXISTS (
      SELECT 1
      FROM THIRD_PARTY_REQUEST r
      WHERE r.REQUEST_ID = l.REQUEST_ID
        AND r.STATUS = 'CANCELLED'
  );

DELETE FROM THIRD_PARTY_REQUEST r
WHERE r.STATUS = 'CANCELLED'
  AND NOT EXISTS (
      SELECT 1
      FROM THIRD_PARTY_FORM_LINK l
      WHERE l.REQUEST_ID = r.REQUEST_ID
  );

COMMIT;
