-- Finalize third-party workflow statuses after the new application package,
-- which writes PENDING_SECTION_HEAD, has been deployed.
-- Run once as SLF_USER.

INSERT INTO THIRD_PARTY_WORKFLOW_ACTION (
    REQUEST_ID,
    ACTION_TYPE,
    FROM_STATUS,
    TO_STATUS,
    ACTOR_TYPE,
    ACTOR_EMPID,
    COMMENT_TEXT,
    ACTED_AT
)
SELECT
    REQUEST_ID,
    'WORKFLOW_MIGRATED',
    STATUS,
    'PENDING_SECTION_HEAD',
    'SYSTEM',
    NULL,
    'Request submitted during deployment migrated into the third-party workflow.',
    SYSTIMESTAMP
FROM THIRD_PARTY_REQUEST
WHERE STATUS = 'SUBMITTED';

UPDATE THIRD_PARTY_REQUEST
SET STATUS = 'PENDING_SECTION_HEAD',
    UPDATED_AT = SYSTIMESTAMP
WHERE STATUS = 'SUBMITTED';

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE THIRD_PARTY_REQUEST DROP CONSTRAINT CHK_THIRD_PARTY_REQ_STATUS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
        END IF;
END;
/

ALTER TABLE THIRD_PARTY_REQUEST ADD CONSTRAINT CHK_THIRD_PARTY_REQ_STATUS CHECK (
    STATUS IN (
        'LINK_CREATED',
        'PENDING_SECTION_HEAD',
        'PENDING_IT_DIRECTOR',
        'PENDING_OPERATOR',
        'PENDING_EXTERNAL_ACCEPTANCE',
        'PENDING_REVOKER',
        'PENDING_REVOKE_REVIEWER',
        'PENDING_SECTION_HEAD_REPORT',
        'PENDING_FINAL_CERTIFICATION',
        'COMPLETED',
        'REJECTED',
        'CANCELLED'
    )
);

COMMIT;
