-- THIRD_PARTY_REQUEST.STATUS is the single source of truth for workflow state.
-- THIRD_PARTY_FORM_SUBMISSION.STATUS was always PENDING_REVIEW and was never
-- updated by the current workflow.

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IX_THIRD_PARTY_SUB_STATUS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1418 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE THIRD_PARTY_FORM_SUBMISSION DROP CONSTRAINT CHK_THIRD_PARTY_SUB_STATUS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE THIRD_PARTY_FORM_SUBMISSION DROP COLUMN STATUS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -904 THEN
            RAISE;
        END IF;
END;
/

COMMIT;
