BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE THIRD_PARTY_ACCEPTANCE_TOKEN ADD RAW_TOKEN VARCHAR2(120)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

COMMIT;
