BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE THIRD_PARTY_REQUEST DROP CONSTRAINT CHK_THIRD_PARTY_REQ_DATES';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
        END IF;
END;
/

ALTER TABLE THIRD_PARTY_REQUEST MODIFY (
    EXTERNAL_COMPANY_NAME NULL,
    EXTERNAL_CONTACT_NAME NULL,
    EXTERNAL_EMAIL NULL,
    EXTERNAL_PHONE NULL,
    PURPOSE NULL,
    TARGET_SYSTEM NULL,
    ACCESS_START_DATE NULL,
    ACCESS_END_DATE NULL
);

ALTER TABLE THIRD_PARTY_REQUEST ADD CONSTRAINT CHK_THIRD_PARTY_REQ_DATES CHECK (
    ACCESS_START_DATE IS NULL OR ACCESS_END_DATE IS NULL OR ACCESS_END_DATE >= ACCESS_START_DATE
);

COMMIT;
