BEGIN
    EXECUTE IMMEDIATE
        'CREATE INDEX IX_TP_REQ_OWNER_UPDATED ON THIRD_PARTY_REQUEST (INTERNAL_OWNER_EMPID, UPDATED_AT DESC, REQUEST_ID DESC)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'CREATE INDEX IX_TP_REQ_UPDATED ON THIRD_PARTY_REQUEST (UPDATED_AT DESC, REQUEST_ID DESC)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'CREATE INDEX IX_TP_LINK_REQUEST_ID ON THIRD_PARTY_FORM_LINK (REQUEST_ID)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

COMMIT;
