ALTER TABLE EMPLOYEE ADD (
    EMAIL_NOTIFICATION_ENABLED NUMBER(1) DEFAULT 1 NOT NULL
);

UPDATE EMPLOYEE
SET EMAIL_NOTIFICATION_ENABLED = 1
WHERE EMAIL_NOTIFICATION_ENABLED IS NULL;

ALTER TABLE EMPLOYEE ADD CONSTRAINT CHK_EMP_EMAIL_NOTI_ENABLED
CHECK (EMAIL_NOTIFICATION_ENABLED IN (0, 1));
