BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_NOTIFICATION_LOG DROP CONSTRAINT CHK_EMAIL_NOTIFICATION_STATUS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2443 THEN
            RAISE;
        END IF;
END;
/

ALTER TABLE EMAIL_NOTIFICATION_LOG ADD CONSTRAINT CHK_EMAIL_NOTIFICATION_STATUS
CHECK (STATUS IN ('READY', 'PENDING', 'SENDING', 'SENT', 'FAILED', 'SKIPPED'));

UPDATE EMAIL_NOTIFICATION_LOG
SET STATUS = 'READY',
    ERROR_MESSAGE = NULL,
    NEXT_ATTEMPT_AT = SYSTIMESTAMP
WHERE STATUS = 'SKIPPED'
  AND ERROR_MESSAGE LIKE 'Gmail notification skipped: set slf.mail.username%';

UPDATE EMAIL_NOTIFICATION_LOG
SET STATUS = 'READY',
    NEXT_ATTEMPT_AT = NVL(NEXT_ATTEMPT_AT, SYSTIMESTAMP)
WHERE STATUS = 'PENDING';

COMMIT;
