-- Consent text is maintained in thirdpartyForm.jsp.
-- This migration stores only the acceptance evidence on each submission.

ALTER TABLE THIRD_PARTY_FORM_SUBMISSION ADD (
    CONSENT_ACCEPTED NUMBER(1) DEFAULT 0 NOT NULL,
    CONSENT_VERSION VARCHAR2(50),
    CONSENT_ACCEPTED_AT TIMESTAMP,
    CONSENT_IP_ADDRESS VARCHAR2(45),
    CONSENT_USER_AGENT VARCHAR2(500)
);

ALTER TABLE THIRD_PARTY_FORM_SUBMISSION ADD CONSTRAINT
    CHK_THIRD_PARTY_SUB_CONSENT_ACCEPTED
    CHECK (CONSENT_ACCEPTED IN (0, 1));
