BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_NOTIFICATION_LOG ADD FORM_TYPE VARCHAR2(30) DEFAULT ''REQUISITION'' NOT NULL';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE EMAIL_NOTIFICATION_LOG ADD REFERENCE_ID NUMBER';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1430 THEN
            RAISE;
        END IF;
END;
/

UPDATE EMAIL_NOTIFICATION_LOG
SET FORM_TYPE = 'REQUISITION'
WHERE FORM_TYPE IS NULL;

UPDATE EMAIL_NOTIFICATION_LOG
SET REFERENCE_ID = FORMID
WHERE REFERENCE_ID IS NULL
  AND FORMID IS NOT NULL;

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_EMAIL_NOTI_LOG_FORM_REF ON EMAIL_NOTIFICATION_LOG (FORM_TYPE, REFERENCE_ID)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

COMMIT;
